default:
  tags: [pr, amd64]

variables:
  TOPIC: "gxd"
  APPLICATION_NAME: "grafana-agent-llm-inspector"
  DAILY_RUN: "false"

.run-if-on-main-branch: &run-if-on-main-branch
  if: '$CI_COMMIT_BRANCH == "main" && $DAILY_RUN == "false"'
  when: on_success

include:
  - project: tsc/tsc-pipeline
    file: /includes/docker-ecr.yaml
    ref: master

  - component: $CI_SERVER_FQDN/tap/cicd-components/docker/build@main
    inputs:
      stage: dockerize
      job_name: 'docker-build:np'
      topic: $TOPIC
      env: int
      registry_type: gitlab
      repository_name: $TOPIC-$APPLICATION_NAME
      rules:
        - <<: *run-if-on-main-branch

  - component: $CI_SERVER_FQDN/tap/cicd-components/docker/release@main
    inputs:
      stage: release
      job_name: 'docker-release:np'
      topic: $TOPIC
      env: int
      registry_type: gitlab
      repository_name: $TOPIC-$APPLICATION_NAME
      rules:
        - if: $CI_COMMIT_TAG && $DAILY_RUN == "false"
          when: on_success

  - component: $CI_SERVER_FQDN/tap/cicd-components/security/scan@main
    inputs:
      stage: sysdigScan
      job_name: scan:gitlab
      needs: [docker-build:np]
      rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule" && $DAILY_RUN == "false"
          when: on_success

daily-run:
  stage: daily-run
  image: ${CI_REGISTRY_IMAGE}/${TOPIC}-${APPLICATION_NAME}:v1.3
  variables:
    # DAILY_RUN: "true"
    APP_CONFIG_PATH: "/app/config/config.example.yaml"
    GRAFANA_URL: "${GRAFANA_URL}"
    GRAFANA_API_KEY: "${GRAFANA_API_KEY}"
    COPILOT_ACCESS_TOKEN: "${COPILOT_ACCESS_TOKEN}"
    SMTP_HOST: "${SMTP_HOST}"
    SMTP_PORT: "${SMTP_PORT}"
    SMTP_USER: "${SMTP_USER}"
    SMTP_PASSWORD: "${SMTP_PASSWORD}"
    EMAIL_FROM: "${EMAIL_FROM}"
  script:
    - grafana-agent-langgraph
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DAILY_RUN == "true"

stages:
  - dockerize
  - release
  - sysdigScan
  - daily-run
